### ISSUE TITLE
Request: Traversing multiple depths of forward/reverse citations

### ISSUE THREAD

**Issue by yutotakano** [sergeyprokudin/scholtrack#1]
Hi! Just found this project in my GitHub feed and tried it out.

It seems great, but the "who cited Paper X?" is rather simple information to get through a manual search as well (e.g. on Google Scholar). 

I'm not sure about the scope of this project for you personally, but I feel like the project would be more beneficial if it allowed traversing citations in a graph-like manner in both forward and reverse direction to a certain depth. For example, you can specify depth=2 and it might come up with a list containing all of:

- "works that cite (paper X)"
- "works that cite (works that cite (paper X))"
- "works that (paper X) cites"
- "works that (works that cite (paper X)) cites"
- "works that cite (works that (paper X) cites)"
- etc. 

Then, some hand-coded algorithm (or LLM!) can sort by the most "influential" or the "newest". I feel this would particularly work well for the use case of getting a field overview or the most recent works in a field!

Do feel free to close this issue if this doesn't align to your goals, it's merely a suggestion that I would find useful, after all!

**Comment by sergeyprokudin** [comment]
Hi @yutotakano,

Thanks for the suggestion! It’s definitely a useful feature. I was initially hesitant to implement it right away because it could easily lead to many unrelated citations. For example, you might have influential papers citing your paper of interest, but they may not be directly related to your specific field. Consider, for instance, a widely cited survey on "Transformers in Deep Learning" that also happens to cite a paper on "3D Transformers" for vision tasks (your original focus). Retrieving all the citations for the general survey would result in a large number of citations that are irrelevant to your focus on 3D applications. Additionally, running a recursive search for papers with numerous citations could be time-consuming. For now, I’ve opted for a manually curated list of key works in the field.

That said, I completely agree that there should be a more efficient way to perform recursive searches - perhaps by using an LLM to determine whether a particular paper on the list is genuinely relevant.

> It seems great, but the "who cited Paper X?" is rather simple information to get through a manual search as well (e.g. on Google Scholar).

Fully agree, that's just a first very basic step. However, the difference with Google Scholar here is that you can search by multiple papers simultaneously, and **feed the resulting CSV to ChatGPT** to ask questions about it, or even simply look for keywords yourself in the big list of downloaded abstracts.  

> some hand-coded algorithm (or LLM!) can sort by the most "influential" or the "newest".

The current tool already allows sorting by date or citation count (as a basic approximation of a paper's influence), just so you know. Simply use `-s arxiv` or `-s citations`.

Thanks again for your interest, and let me know if you have any other ideas or suggestions for improvement!

~Sergey
